---
driver:
  name: vagrant
  network:
  - ["forwarded_port", {guest: 9392, host: 9392, auto_correct: true}]

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
#  - name: centos-6.4

suites:
  - name: openvas-client
    run_list:
      - recipe[openvas::default]
    attributes:
  - name: openvas-server
    run_list:
      - recipe[openvas::server]
    attributes:
      openvas:
        enable_nvt_updates_from_cron: "yes"
        enable_greenbone_scan_configs: "yes"
        nasl_no_signature_check: "yes"
  - name: openvas-source
    run_list:
      - recipe[openvas::source]
    attributes:
