---
driver:
  name: vagrant
  network:
  - ["forwarded_port", {guest: 9392, host: 9392}]

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
#  - name: centos-6.4

suites:
  - name: openvas-client
    run_list:
      - recipe[openvas::default]
    attributes:
  - name: openvas-server
    run_list:
      - recipe[openvas::nmap]
      - recipe[openvas::server]
